databases:
  - name: django_crud
    databaseName: django_crud
    user: django_crud

services:
  - type: web
    name: mysite
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn django_crud.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django_crud
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4